name: Build Nextcloud Custom

on:
  schedule:
    - cron: "0 3 * * *"   # ogni giorno alle 03:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/sudokuinsonne/nextcloud-custom:latest .

      - name: Push image
        run: |
          docker push ghcr.io/sudokuinsonne/nextcloud-custom:latest
